plot_configs:
  general:
    dpi: 75
    dpi_save: 300
    legend_fontsize: 12
    legend_fontweight: bold
    title_fontsize: 14
    title_fontweight: bold
    font_family: "DejaVu Sans"
  embeddings_plots:
    alpha: 0.75
    frameon: false
    add_outline: true
    layer: log_norm
    legend_fontsize: 12
    outline_color: [black, white]
    outline_width: [.2, .025]
    ncols: 1
    vmax: 'p98'
    cmap: viridis
    na_color: white
    na_in_legend: false
  continuous_plots:
    layer: log_norm
    var_group_rotation: 90
    cmap: viridis
  rank_genes_plots:
    values_to_plot: logfoldchanges
    vmin: -5
    vmax: 5
    var_group_rotation: 90
    min_logfoldchange: 2
    cmap: bwr
palettes:
  continuous: viridis
  divergent: bwr
  Level_2:
    Lymphoid: "#028E95"
    Myeloid: "#f56d18"
    Malignant Cell: "#ff0000"
    Stromal Cell: "#25e907"
    Endothelial Cell: "#9c0101"
    Exocrine Cell: "#ea7b95"
    Endocrine Cell: "#f5d276"
  Level_3: ##updated by daniele
    Macrophage:                   "#8b4513"
    Acinar (REG+) Cell:           "#8a2be2"
    Malignant Cell - Mesenchymal: "#483d8b"
    B Cell:                       "#b03060"
    Cancer Associated Fibroblast: "#dc143c"
    Malignant Cell - Epithelial:  "#008b8b"
    Monocyte:                     "#808000"
    Epsilon Cell:                 "#ff8c00"
    CD4+ T Cell:                  "#8fbc8f"
    Ductal Cell:                  "#ffd700"
    Ductal Cell (atypical):       "#00ff00"
    Fibroblast:                   "#dc143c"
    NK Cell:                      "#ff4500"
    Mixed T Cell:                 "#800080"
    Gamma Cell:                   "#add8e6"
    CD8+ T Cell:                  "#00008b"
    Neutrophil:                   "#006400"
    Malignant Cell - EMT:         "#bc8f8f"
    Endothelial Cell:             "#dda0dd"
    Alpha Cell:                   "#1e90ff"
    ADM Cell:                     "#00ff00"
    Dendritic Cell:               "#00fa9a"
    Beta Cell:                    "#ff00ff"
    Acinar Idling Cell:           "#dc143c"
    Delta Cell:                   "#00bfff"
    Acinar Cell:                  "#00ffff"
    Plasma Cell:                  "#0000ff"
    Adipocyte:                    "#adff2f"
    Mast Cell:                    "#ffe4c4"
    Other Endocrine:              "#000000"
    Pericyte:                     "#ff1493"
    Schwann Cell:                 "#a5a5a5"
    Smooth Muscle Cell:           "#b22222"


  Level_4:
    'Acinar (REG+) Cell': '#a6cee3'
    'Acinar Cell': '#b2df8a'
    'Acinar Idling Cell': '#fdbf6f'
    'ADM Cell': '#cab2d6'
    'Adipocyte': '#ffff99'
    'Alpha Cell': '#b15928'
    'apCAF': '#1f78b4'
    'B Cell - Activated': '#1f78b4'
    'B Cell - Germinal Center': '#33a02c'
    'B Cell - Memory': '#e31a1c'
    'B Cell - Naive': '#6a3d9a'
    'B-reg': '#b15928'
    'Beta Cell': '#1f78b4'
    'CD4+ Memory T Cell': '#a6cee3'
    'CD4+ Naive T Cell': '#b2df8a'
    'CD4+ Th1 Cell': '#fb9a99'
    'CD4+ Th17 Cell': '#e31a1c'
    'CD4+ Th2 Cell': '#cab2d6'
    'CD4+ Th22 Cell': '#1f78b4'
    'CD8+ Effector T Cell': '#a6cee3'
    'CD8+ Memory T Cell': '#b2df8a'
    'CD8+ Naive T Cell': '#fb9a99'
    'CD8+ Terminal Effector T Cell': '#cab2d6'
    'CD8+ Tissue-Resident Memory T Cell': '#b15928'
    'CD8+ Exhausted T Cell': '#33a02c' 
    'Dendritic Cell - Activated': '#e377c2'
    'Dendritic Cell - cDC1': '#1f78b4'
    'Dendritic Cell - cDC2': '#e31a1c'
    'Dendritic Cell - pDC': '#6a3d9a'
    'Delta Cell': '#bcbd22'
    'Double Positive CD4+CD8+ T Cell': '#e31a1c'
    'Ductal Cell': '#17becf'
    'Ductal Cell (atypical)': '#9edae5'
    'Epsilon Cell': '#393b79'
    'Fibroblast': '#5254a3'
    'Gamma Cell': '#6b6ecf'
    'γδ T Cell (Vδ1)': '#6a3d9a'
    'iCAF': '#9c9ede'
    'Lymphatic Endothelial Cell': '#637939'
    'Macrophage - angiogenic TAM': '#1f78b4'
    'Macrophage - antigen processing TAM': '#ff7f00'
    'Macrophage - CD3+ TAM': '#e31a1c'
    'Macrophage - C1Q+ TAM': '#6a3d9a'
    'Macrophage - lipid processing TAM': '#b15928'
    'Malignant Cell - Pit Like': "#a6cee3"
    'Malignant Cell - Acinar-like': "#b2df8a"
    'Malignant Cell - Epithelial': "#fb9a99"
    'Malignant Cell - Hypoxia': "#fdbf6f"
    'Malignant Cell - EMT': "#cab2d6"
    'Malignant Cell - Highly Proliferative': "#e31a1c"
    'Malignant Cell - Mesenchymal': "#fed683"
    'Malignant Cell - Highly Invasive': "#6a3d9a"
    'Malignant Cell - Senescence': "#1f78b4"
    'Malignant Cell - Apoptotic': "#b15928"
    'Mast Cell': '#393b79'
    'Monocyte': '#6b6ecf'
    'myCAF': '#9c9ede'
    'Neutrophil - N0': '#1f78b4'
    'Neutrophil - N1': '#33a02c'
    'Neutrophil - N2': '#b15928'
    'NK Cell': '#cedb9c'
    'Other Endocrine': '#8c6d31'
    'Pericyte': '#bd9e39'
    'Plasma Cell': '#e7ba52'
    'Plasmablast': '#e7969c'
    'Schwann Cell': '#843c39'
    'Smooth Muscle Cell': '#ad494a'
    'T-reg': '#b15928'
    'Tumor-Associated Endothelial Cell': '#7b4173'
    'Vascular Endothelial Cell': '#a55194'

  Level_4_Daniele_2:
    'Macrophage - C1Q+ TAM': '#006400'
    'Macrophage - antigen processing TAM': '#00008b'
    'Acinar (REG+) Cell': '#006400'
    'Malignant Cell - Mesenchymal': '#006400'
    'B Cell - Naive': '#006400'
    'myCAF': '#006400'
    'Malignant Cell - Pit Like': '#006400'
    'Malignant Cell - Hypoxia': '#00008b'
    'Monocyte': '#006400'
    'Malignant Cell - Highly Proliferative': '#ff0000'
    'B-reg': '#00008b'
    'Epsilon Cell': '#006400'
    'γδ T Cell (Vδ1)': '#006400'
    'Ductal Cell': '#006400'
    'CD4+ Th1 Cell': '#00008b'
    'Fibroblast': '#006400' 
    'NK Cell': '#006400' 
    'B Cell - Activated': '#ff0000' 
    'Double Positive CD4+CD8+ T Cell': '#006400' 
    'Gamma Cell': '#006400' 
    'CD8+ Naive T Cell': '#006400' 
    'Neutrophil - N1': '#006400' 
    'Malignant Cell - EMT': '#006400' 
    'Neutrophil - N0': '#00008b' 
    'Vascular Endothelial Cell': '#006400'
    'Malignant Cell - Senescence': '#ff4500' 
    'Alpha Cell': '#006400' 
    'CD4+ Th22 Cell': '#ff0000' 
    'CD8+ Exhausted T Cell': '#00008b' 
    'Macrophage - angiogenic TAM': '#ff0000' 
    'Malignant Cell - Apoptotic': '#ffd700' 
    'Malignant Cell - Epithelial': '#00ff00' 
    'T-reg': '#ff4500' 
    'Macrophage - CD3+ TAM': '#ff4500' 
    'ADM Cell': '#006400' 
    'Malignant Cell - Highly Invasive': '#00008b' 
    'Dendritic Cell - cDC1': '#006400' 
    'Lymphatic Endothelial Cell': '#00008b' 
    'CD4+ Naive T Cell': '#ffd700' 
    'Macrophage - lipid processing TAM': '#ffd700' 
    'CD4+ Th17 Cell': '#00ff00' 
    'Malignant Cell - Acinar-like': '#c71585' 
    'apCAF': '#00008b' 
    'Beta Cell': '#006400' 
    'CD4+ Th2 Cell': '#c71585' 
    'Tumor-Associated Endothelial Cell': '#ff0000' 
    'Neutrophil - N2': '#ff0000' 
    'B Cell - Memory': '#ff4500' 
    'Acinar Idling Cell': '#006400' 
    'CD8+ Tissue-Resident Memory T Cell': '#ff0000' 
    'iCAF': '#ff0000' 
    'CD4+ Memory T Cell': '#6495ed' 
    'Dendritic Cell - pDC': '#00008b' 
    'CD8+ Effector T Cell': '#ff4500' 
    'Dendritic Cell - cDC2': '#ff0000' 
    'Delta Cell': '#006400' 
    'Acinar Cell': '#006400' 
    'CD8+ Terminal Effector T Cell': '#ffd700' 
    'CD8+ Memory T Cell': '#00ff00' 
    'Plasma Cell': '#006400' 
    'Adipocyte': '#006400' 
    'Mast Cell': '#006400' 
    'Plasmablast': '#00008b' 
    'Macrophage - antigen processing TAM': '#00ff00' 
    'Schwann Cell': '#006400' 
    'Ductal Cell (atypical)': '#006400'
    'B Cell - Germinal Center': '#ffd700' 
    'Other Endocrine': '#006400' 
    'Dendritic Cell - Activated': '#ff4500' 
    'Pericyte': '#006400' 
    'Smooth Muscle Cell': '#006400'

  Level_4_old:
    CD4+ Naive T Cell: "#496aaf"
    CD4+ Th1 Cell: "#47a0b3"
    CD4+ Th2 Cell: "#7ecca5"
    CD4+ Th17 Cell: "#bfe5a0"
    CD4+ Th22 Cell: "#edf8a3"
    T-reg: "#fff7b2"
    CD4+ Memory T Cell: "#fed683"
    CD8+ Naive T Cell: "#496aaf"
    CD8+ Effector T Cell: "#60bba8"
    CD8+ Terminal Effector T Cell: "#bfe5a0"
    CD8+ Exhausted T Cell: "#f9fcb5"
    CD8+ Tissue-Resident Memory T Cell: "#fed683"
    CD8+ Memory T Cell: "#f7844e"
    Double Positive CD4+CD8+ T Cell: "#496aaf"
    γδ T Cell (Vδ1): "#fff7b2"
    B Cell - Naive: "#496aaf"
    B Cell - Activated: "#a2d9a4"
    B Cell - Memory: "#fff7b2"
    B-reg: "#f7844e"
    Plasma Cell: "#b81e48"
    Monocyte: "#b81e48"
    Macrophage - lipid processing TAM: "#496aaf"
    Macrophage - antigen processing TAM: "#7ecca5"
    Macrophage - C1Q+ TAM: "#edf8a3"
    Macrophage - angiogenic TAM: "#fed683"
    Macrophage - CD3+ TAM: "#f06744"
    Dendritic Cell - pDC: "#496aaf"
    Dendritic Cell - cDC1: "#bfe5a0"
    Dendritic Cell - cDC2: "#fed683"
    Neutrophil - N0: "#496aaf"
    Neutrophil - N1: "#bfe5a0"
    Neutrophil - N2: "#fed683"
    NK Cell: "#b81e48"
    Lymphatic Endothelial Cell: "#496aaf"
    Vascular Endothelial Cell: "#bfe5a0"
    Tumor-Associated Endothelial Cell: "#fed683"
    Malignant Cell - Pit Like: "#496aaf"
    Malignant Cell - Acinar-like: "#47a0b3"
    Malignant Cell - Epithelial: "#7ecca5"
    Malignant Cell - Hypoxia: "#bfe5a0"
    Malignant Cell - EMT: "#edf8a3"
    Malignant Cell - Highly Proliferative: "#fff7b2"
    Malignant Cell - Mesenchymal: "#fed683"
    Malignant Cell - Highly Invasive: "#fca55d"
    Malignant Cell - Senescence: "#f06744"
    Malignant Cell - Apoptotic: "#d23a4e"
    Pericyte: "#496aaf"
    Schwann Cell: "#60bba8"
    Fibroblast: "#bfe5a0"
    apCAF: "#f9fcb5"
    iCAF: "#fed683"
    myCAF: "#f7844e"
    Acinar Cell: "#496aaf"
    Acinar Idling Cell: "#bfe5a0"
    Acinar (REG+) Cell: "#fed683"
    ADM Cell: "#b81e48"
    Ductal Cell: "#496aaf"
    Ductal Cell (atypical): "#fff7b2"
    Alpha Cell: "#b81e48"
    Beta Cell: "#b81e48"
    Gamma Cell: "#b81e48"
    Delta Cell: "#b81e48"
    Epsilon Cell: "#b81e48"
    Adipocyte: "#b81e48"

  Model: #added by philipp
    orthotopic: "#0072B2"  # Blue
    endogenous:   "#D55E00"   # Vermillion

  Data_Source: #added by philipp
    in house:      "#d55607" #
    public data:   "#f6a974" # Grey

  Dataset: #added by philipp
    in_house:      "#56B4E9" # Sky Blue
    Chen_2024:     "#E69F00"  # Orange
    Donahue_2024:  "#009E73"  # Green
    Rupert_2025:   "#F0E442"  # Yellow
    Chen_2021:     "#CC79A7"  # Pink
    Carstens_2021: "#999999"  # Grey
    Han_2023:      "#B79F00"  # Olive 
    Erdem_2024:    "#A65628"  # Brown

  TreatmentStatus: #added by philipp
    Untreated: "#999999"  #  Grey
    Treated:   "#E41A1C"     # Vivid Red

  TreatmentType: ##added by philipp
    Untreated: "#999999"  # Grey
    Chemotherapy: "#0b559f"
    Chemotherapy + Radiotherapy: "#5fa8d3"
    Chemotherapy + Radiotherapy + Immunotherapy: "#bad6eb"
    Other: "#ff7f00"

  Is_Core: ##added by philipp
    Core: "#0b559f"
    Extension: "#bad6eb"

  Sex: #added by philipp
    male: "#56B4E9"
    female: "#CC79A7"

  
  
###dark blue for public
