plot_configs:
  general:
    dpi: 75
    dpi_save: 300
    legend_fontsize: 12
    legend_fontweight: bold
    title_fontsize: 14
    title_fontweight: bold
    font_family: "DejaVu Sans"
  embeddings_plots:
    alpha: 0.75
    frameon: false
    add_outline: true
    layer: log_norm
    legend_fontsize: 12
    outline_color: [black, white]
    outline_width: [.2, .025]
    ncols: 1
    vmax: 'p98'
    cmap: viridis
    na_color: white
    na_in_legend: false
  continuous_plots:
    layer: log_norm
    var_group_rotation: 90
    cmap: viridis
  rank_genes_plots:
    values_to_plot: logfoldchanges
    vmin: -5
    vmax: 5
    var_group_rotation: 90
    min_logfoldchange: 2
    cmap: bwr
palettes:
  continuous: viridis
  divergent: bwr
  Level_2:
    Lymphoid: "#028E95"
    Myeloid: "#f56d18"
    Malignant Cell: "#ff0000"
    Stromal Cell: "#25e907"
    Endothelial Cell: "#9c0101"
    Exocrine Cell: "#ea7b95"
    Endocrine Cell: "#f5d276"
  Level_3: ##updated by daniele
    Macrophage:                   "#8b4513"
    Acinar (REG+) Cell:           "#8a2be2"
    Malignant Cell - Mesenchymal: "#483d8b"
    B Cell:                       "#b03060"
    Cancer Associated Fibroblast: "#dc143c"
    Malignant Cell - Epithelial:  "#008b8b"
    Monocyte:                     "#808000"
    Epsilon Cell:                 "#ff8c00"
    CD4+ T Cell:                  "#8fbc8f"
    Ductal Cell:                  "#ffd700"
    Ductal Cell (atypical):       "#00ff00"
    Fibroblast:                   "#dc143c"
    NK Cell:                      "#ff4500"
    Mixed T Cell:                 "#800080"
    Gamma Cell:                   "#add8e6"
    CD8+ T Cell:                  "#00008b"
    Neutrophil:                   "#006400"
    Malignant Cell - EMT:         "#bc8f8f"
    Endothelial Cell:             "#dda0dd"
    Alpha Cell:                   "#1e90ff"
    ADM Cell:                     "#00ff00"
    Dendritic Cell:               "#00fa9a"
    Beta Cell:                    "#ff00ff"
    Acinar Idling Cell:           "#dc143c"
    Delta Cell:                   "#00bfff"
    Acinar Cell:                  "#00ffff"
    Plasma Cell:                  "#0000ff"
    Adipocyte:                    "#adff2f"
    Mast Cell:                    "#ffe4c4"
    Other Endocrine:              "#000000"
    Pericyte:                     "#ff1493"
    Schwann Cell:                 "#a5a5a5"
    Smooth Muscle Cell:           "#b22222"

  Level_4:
    CD4+ Naive T Cell: "#496aaf"
    CD4+ Th1 Cell: "#47a0b3"
    CD4+ Th2 Cell: "#7ecca5"
    CD4+ Th17 Cell: "#bfe5a0"
    CD4+ Th22 Cell: "#edf8a3"
    T-reg: "#fff7b2"
    CD4+ Memory T Cell: "#fed683"
    CD8+ Naive T Cell: "#496aaf"
    CD8+ Effector T Cell: "#60bba8"
    CD8+ Terminal Effector T Cell: "#bfe5a0"
    CD8+ Exhausted T Cell: "#f9fcb5"
    CD8+ Tissue-Resident Memory T Cell: "#fed683"
    CD8+ Memory T Cell: "#f7844e"
    Double Positive CD4+CD8+ T Cell: "#496aaf"
    γδ T Cell (Vδ1): "#fff7b2"
    B Cell - Naive: "#496aaf"
    B Cell - Activated: "#a2d9a4"
    B Cell - Memory: "#fff7b2"
    B-reg: "#f7844e"
    Plasma Cell: "#b81e48"
    Monocyte: "#b81e48"
    Macrophage - lipid processing TAM: "#496aaf"
    Macrophage - antigen processing TAM: "#7ecca5"
    Macrophage - C1Q+ TAM: "#edf8a3"
    Macrophage - angiogenic TAM: "#fed683"
    Macrophage - CD3+ TAM: "#f06744"
    Dendritic Cell - pDC: "#496aaf"
    Dendritic Cell - cDC1: "#bfe5a0"
    Dendritic Cell - cDC2: "#fed683"
    Neutrophil - N0: "#496aaf"
    Neutrophil - N1: "#bfe5a0"
    Neutrophil - N2: "#fed683"
    NK Cell: "#b81e48"
    Lymphatic Endothelial Cell: "#496aaf"
    Vascular Endothelial Cell: "#bfe5a0"
    Tumor-Associated Endothelial Cell: "#fed683"
    Malignant Cell - Pit Like: "#496aaf"
    Malignant Cell - Acinar-like: "#47a0b3"
    Malignant Cell - Epithelial: "#7ecca5"
    Malignant Cell - Hypoxia: "#bfe5a0"
    Malignant Cell - EMT: "#edf8a3"
    Malignant Cell - Highly Proliferative: "#fff7b2"
    Malignant Cell - Mesenchymal: "#fed683"
    Malignant Cell - Highly Invasive: "#fca55d"
    Malignant Cell - Senescence: "#f06744"
    Malignant Cell - Apoptotic: "#d23a4e"
    Pericyte: "#496aaf"
    Schwann Cell: "#60bba8"
    Fibroblast: "#bfe5a0"
    apCAF: "#f9fcb5"
    iCAF: "#fed683"
    myCAF: "#f7844e"
    Acinar Cell: "#496aaf"
    Acinar Idling Cell: "#bfe5a0"
    Acinar (REG+) Cell: "#fed683"
    ADM Cell: "#b81e48"
    Ductal Cell: "#496aaf"
    Ductal Cell (atypical): "#fff7b2"
    Alpha Cell: "#b81e48"
    Beta Cell: "#b81e48"
    Gamma Cell: "#b81e48"
    Delta Cell: "#b81e48"
    Epsilon Cell: "#b81e48"
    Adipocyte: "#b81e48"

  Model: #added by philipp
    orthotopic: "#0072B2"  # Blue
    endogenous:   "#D55E00"   # Vermillion

  Data_Source: #added by philipp
    in house:      "#56B4E9" # Sky Blue
    public data:   "#999999" # Grey

  Dataset: #added by philipp
    in_house:      "#56B4E9" # Sky Blue
    Chen_2024:     "#E69F00"  # Orange
    Donahue_2024:  "#009E73"  # Green
    Rupert_2025:   "#F0E442"  # Yellow
    Chen_2021:     "#CC79A7"  # Pink
    Carstens_2021: "#999999"  # Grey
    Han_2023:      "#B79F00"  # Olive 
    Erdem_2024:    "#A65628"  # Brown

  TreatmentStatus: #added by philipp
    Untreated: "#BBBBBB"  # Light Grey
    Treated:   "#E41A1C"     # Vivid Red

  

